Aquí simplemente obtenemos el conjunto de entrenamiento y test y lo guardamos en archivos de Excel distintos.

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
file_path_name = "dataset/DATASET_xyz.xlsx"
df = pd.read_excel(file_path_name)

In [3]:
cols_duplicadas = ['fc [Mhz]', 'elevation', 'azimuth', 'hour', 'mmdd_sin','mmdd_cos','hour_sin','hour_cos']

# Creamos una "máscara" (True si es duplicada, False si es única/original)
# keep='first' marca como True (duplicada) todas las apariciones MENOS la primera.
mask_duplicadas = df.duplicated(subset=cols_duplicadas, keep='first')
cant_duplicadas = mask_duplicadas.sum()

print(f"--- REPORTE DE DUPLICADOS ---")

if cant_duplicadas > 0:
    print(f"Se detectaron {cant_duplicadas} filas repetidas que serán eliminadas.")
    
    # 3. VISUALIZACIÓN: Mostramos una muestra de lo que se va a borrar
    print("\n--- Muestra de filas a eliminar (Primeras 5) ---")
    # Creamos un dataframe temporal solo con las duplicadas para visualizarlas
    # Mostramos solo las columnas clave para verificar rápido, pero puedes quitar el filtro de columnas
    filas_a_borrar = df[mask_duplicadas]
    print(filas_a_borrar[cols_duplicadas].head()) 
    
    # 4. ACCIÓN: Eliminamos usando la inversa de la máscara (~)
    # Esto es equivalente a drop_duplicates pero más explícito ya que calculamos la máscara antes
    df = df[~mask_duplicadas]
    
    print(f"\n Limpieza completada. Filas restantes: {df.shape[0]}")

else:
    print("No se encontraron duplicados. Todo en orden.")

print("-----------------------------")

--- REPORTE DE DUPLICADOS ---
Se detectaron 2 filas repetidas que serán eliminadas.

--- Muestra de filas a eliminar (Primeras 5) ---
     fc [Mhz]  elevation  azimuth  hour  mmdd_sin  mmdd_cos  hour_sin  \
939        10          5       98     4     0.425 -0.905193  0.866025
940        10          5       98     8     0.425 -0.905193  0.866025

     hour_cos
939       0.5
940      -0.5

 Limpieza completada. Filas restantes: 37470
-----------------------------

In [4]:
df.head()

,fc [Mhz],elevation,azimuth,hour,day_of_year,mmdd_sin,mmdd_cos,hour_sin,hour_cos,mmdd_modified,...,z_191,z_192,z_193,z_194,z_195,z_196,z_197,z_198,z_199,z_200
0,10,5,98,0,1,0.017213,0.999852,0.000000e+00,1.0,2010-01-01,...,1.065253e+07,1.067038e+07,1.068817e+07,1.070590e+07,1.072357e+07,1.074119e+07,1.075874e+07,1.077624e+07,1.079437e+07,1.081106e+07
1,10,5,98,4,1,0.017213,0.999852,8.660254e-01,0.5,2010-01-01,...,1.096738e+07,1.098593e+07,1.100442e+07,1.102283e+07,1.104117e+07,1.105944e+07,1.107764e+07,1.109577e+07,1.111383e+07,1.113181e+07
2,10,5,98,8,1,0.017213,0.999852,8.660254e-01,-0.5,2010-01-01,...,8.704220e+06,8.717954e+06,8.731673e+06,8.745378e+06,8.759069e+06,8.772758e+06,8.787368e+06,8.801486e+06,8.813465e+06,8.827303e+06
3,10,5,98,12,1,0.017213,0.999852,1.224647e-16,-1.0,2010-01-01,...,8.659012e+06,8.672584e+06,8.686142e+06,8.699686e+06,8.713216e+06,8.726732e+06,8.740234e+06,8.753723e+06,8.767198e+06,8.780291e+06
4,10,5,98,16,1,0.017213,0.999852,-8.660254e-01,-0.5,2010-01-01,...,8.699838e+06,8.713556e+06,8.727259e+06,8.740948e+06,8.754623e+06,8.768285e+06,8.781933e+06,8.795565e+06,8.809243e+06,8.822782e+06

In [5]:
x_columns = ['fc [Mhz]', 'elevation', 'azimuth','mmdd_modified', 'hour',
                      'day_of_year', 'mmdd_sin', 'mmdd_cos', 'hour_sin', 'hour_cos']
# Quitamos las columnas que no son de interes 
x_df = df[x_columns]
# quitamos las columnas de entrada. 
y_df = df.drop(columns=x_columns)

In [6]:
x_df.head()

,fc [Mhz],elevation,azimuth,mmdd_modified,hour,day_of_year,mmdd_sin,mmdd_cos,hour_sin,hour_cos
0,10,5,98,2010-01-01,0,1,0.017213,0.999852,0.000000e+00,1.0
1,10,5,98,2010-01-01,4,1,0.017213,0.999852,8.660254e-01,0.5
2,10,5,98,2010-01-01,8,1,0.017213,0.999852,8.660254e-01,-0.5
3,10,5,98,2010-01-01,12,1,0.017213,0.999852,1.224647e-16,-1.0
4,10,5,98,2010-01-01,16,1,0.017213,0.999852,-8.660254e-01,-0.5

In [7]:
x_train,x_test,y_train,y_test = train_test_split(x_df,y_df,test_size=0.2,random_state=42)

In [8]:
x_train.to_excel("Train_Test/Dataset_separado_xyz/x_train_new.xlsx",index = False)
x_test.to_excel("Train_Test/Dataset_separado_xyz/x_test_new.xlsx",index = False)
y_train.to_excel("Train_Test/Dataset_separado_xyz/y_train_new.xlsx",index = False)
y_test.to_excel("Train_Test/Dataset_separado_xyz/y_test_new.xlsx",index = False)